---
##################################################
# Executes JUnit 5 tests created in the repository
#
# Make sure in your pom file that you set your properties
# 	<properties>
#		  <maven.compiler.source>11</maven.compiler.source>
#		  <maven.compiler.target>11</maven.compiler.target>
#	  </properties>
#
# And you import your dependencies
#  		<dependency>
# 			<groupId>org.junit.jupiter</groupId>
# 			<artifactId>junit-jupiter-api</artifactId>
# 			<version>5.7.2</version>
# 			<scope>test</scope>
#		  </dependency>
#		  <dependency>
#		  	<groupId>org.junit.jupiter</groupId>
#		  	<artifactId>junit-jupiter-engine</artifactId>
#		  	<version>5.7.2</version>
#		  	<scope>test</scope>
#		  </dependency>
#
# And finally you use surefire to run tests in your build section
#  	<build>
#     <plugins>
#        <plugin>
#            <groupId>org.apache.maven.plugins</groupId>
#            <artifactId>maven-surefire-plugin</artifactId>
#            <version>2.22.2</version>
#        </plugin>
#    </plugins>
#   </build>
#
# update the versions as appropriate

name: Run JUnit Tests
on: [workflow_dispatch]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      # Setup Java version, this should always sync to our approved version
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Cache to speed up reuse
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Execute the tests with Maven
      - name: Run tests with Maven
        run: mvn clean test --file pom.xml
      # Publish the test Report
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
